name: clang windows

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '20 3 * * *'


env:
  TEST_DIR: tests


jobs:
  all:
    strategy:
      fail-fast: false
      matrix:
        clang_version: [17, 18]
        cpp_version: [c++17, c++20]
        buildmode: [~ ,  -O3 -DNDEBUG,  -O3 -DNDEBUG -ffast-math]

        # Also include a few variations with disabled UB tricks (not for all to limit resource consumption).
        include:
          - clang_version: 18
            cpp_version: c++20
            buildmode: -DTINY_OPTIONAL_USE_SEPARATE_BOOL_INSTEAD_OF_UB_TRICKS
        
    runs-on: windows-2022
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    - name: Install clang
      uses: KyleMayes/install-llvm-action@v2.0.3
      with:
        version: ${{ matrix.clang_version }}
    - name: Build and run tests
      working-directory: ${{env.TEST_DIR}}
      env:
        CXX: clang++
        ADDITIONAL_FLAGS: ${{ format('-std={0} {1}', matrix.cpp_version, matrix.buildmode) }}
        OUT_DIR_NAME: win_clang_generic
      run: |
        & ".\make_win_gcclike.ps1"
