name: msvc windows

on:
  push:
  pull_request:
  workflow_dispatch:


env:
  TEST_DIR: tests


jobs:
  all:
    strategy:
      fail-fast: false
      matrix:
        cpp_version: [C++17, C++20]
        platform: [x64, Win32]
        buildmode: [Debug, Release]

    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build
      working-directory: ${{env.TEST_DIR}}
      run: msbuild /m /p:Configuration="Msvc ${{ matrix.buildmode }} ${{ matrix.cpp_version }}" /p:Platform=${{matrix.platform}} tiny-optional.sln
    - name: Execute
      working-directory: ${{env.TEST_DIR}}
      run: |
        & "../bin/Msvc ${{ matrix.buildmode }} ${{ matrix.cpp_version }} ${{matrix.platform}}/Tests.exe"
