name: gcc windows

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '20 3 * * *'


env:
  TEST_DIR: tests


jobs:
  all:
    strategy:
      fail-fast: false
      matrix:
        cpp_version: [c++17, c++20]
        # Note: We are never building without optimizations because mingw complains that the object
        # files become too big.
        buildmode: [-O2,  -O3 -DNDEBUG,  -O3 -DNDEBUG -ffast-math]

    runs-on: windows-2022
    timeout-minutes: 15

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2.22.0
      with:
        msystem: mingw64
        install: mingw-w64-x86_64-toolchain make
    - name: Print compiler version
      run: g++ --version
    - name: Build and run tests
      working-directory: ${{env.TEST_DIR}}
      env:
        CXX: g++
        ADDITIONAL_FLAGS: ${{ format('-Wa,-mbig-obj  -std={0} {1}', matrix.cpp_version, matrix.buildmode) }}
        IS_MSYS: 1
      run: make generic
