name: gcc linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
  
env:
  TEST_DIR: ./tests
  TIMEOUT_IN_MINUTES: 10


jobs:
  # Several jobs instead of steps to run them in parallel
  gcc_x64_cpp20:
    runs-on: ubuntu-latest
    timeout-minutes: ${{env.TIMEOUT_IN_MINUTES}}
    steps:
    - uses: actions/checkout@v3
    - name: Build and run gcc_x64_cpp20
      working-directory: ${{env.TEST_DIR}}
      run: make gcc_x64_cpp20
      
  gcc_x64_cpp17:
    runs-on: ubuntu-latest
    timeout-minutes: ${{env.TIMEOUT_IN_MINUTES}}
    steps:
    - uses: actions/checkout@v3
    - name: Build and run gcc_x64_cpp17
      working-directory: ${{env.TEST_DIR}}
      run: make gcc_x64_cpp17
   