name: msvc windows

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '20 3 * * *'


env:
  TEST_DIR: tests


jobs:
  all:
    strategy:
      fail-fast: false
      matrix:
        cpp_version: [C++17, C++20]
        platform: [x64, Win32]
        buildmode: [Debug, Release]

        include:
        - cpp_version: "C++17 permissive"
          platform: x64
          buildmode: Debug
        - cpp_version: "C++20 permissive"
          platform: x64
          buildmode: Debug


    runs-on: windows-2022
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Build
      working-directory: ${{env.TEST_DIR}}
      run: msbuild /m /p:Configuration="Msvc ${{ matrix.buildmode }} ${{ matrix.cpp_version }}" /p:Platform=${{matrix.platform}} tiny-optional.sln
    - name: Execute
      working-directory: ${{env.TEST_DIR}}
      run: |
        & "../bin/Msvc ${{ matrix.buildmode }} ${{ matrix.cpp_version }} ${{matrix.platform}}/Tests.exe"
