name: clang linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  # Several jobs instead of steps to run them in parallel
  clang_x64_cpp17_gcclib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and run clang_x64_cpp17_gcclib
      working-directory: ./tests
      run: make clang_x64_cpp17_gcclib
      
  clang_x64_cpp20_gcclib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and run clang_x64_cpp20_gcclib
      working-directory: ./tests
      run: make clang_x64_cpp20_gcclib
    